# Generated by Django 4.0.4 on 2022-04-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название Тега')),
                ('color', models.CharField(choices=[('#0000FF', '#0000FF'), ('#FF7F50', '#FF7F50'), ('#FFD700', '#FFD700'), ('#008000', '#008000'), ('#00FF00', '#00FF00'), ('#808000', '#808000'), ('#FFA500', '#FFA500'), ('#FFC0CB', '#FFC0CB'), ('#FF0000', '#FF0000'), ('#FFFF00', '#FFFF00')], default='#0000FF', max_length=10, verbose_name='Цвет')),
                ('slug', models.SlugField(unique=True, verbose_name='Поле Slug')),
            ],
        ),
    ]
